site_name: Actividades
dev_addr: 127.0.0.1:8001
# site_url: 
# repo_url: 
# repo_name: <i class="fa fa-git"></i>

theme:
    name: mkdocs
    custom_dir: resources/
extra_css:
    - css/page.css
nav:
    - Individuales:
        - Actividad 1: individual/Actividad 1.md
        - Actividad 2: individual/Actividad 2.md
        - Bonus 1: individual/Bonus 1.md
        - Bonus 2: individual/Bonus 2.md
    - Colaborativas:
        - Actividad 1: todo.md
copyright: Daniel J
site_author: dj
